### ISSUE TITLE
AttributeError: module 'banduppy' has no attribute 'UnfoldingPath'. 

### ISSUE THREAD

**Issue by josueclavijo** [band-unfolding/banduppy#30]
First of all, thanks to Stepan and all collabs for developing this exciting BandUPpy code.

Excuse me if my question is a very basic  one, but really i don't know what i'm missing to do in order to get past of this error:

Traceback (most recent call last):
  File "/home/zephyrus/Descargas/Si-for-banduppy/./run_banduppy.py", line 18, in <module>
    unfold_path=banduppy.UnfoldingPath(
AttributeError: module 'banduppy' has no attribute 'UnfoldingPath'. Did you mean: 'Unfolding'?

I'm trying to use banduppy to unfold supercell structures coming from DFT using Quantum Espresso 7.3., after having banduppy and irrep packages installed via pip.

Any advice will be greatly appreciated.

Regards, 

Josh

**Comment by stepan-tsirkin** [comment]
Hi, 

the structure of the code has chamged in recent versions, so, please try to follow the updated tutorials:
https://github.com/band-unfolding/banduppy/tree/master/tutorials

It is generally the same for QE and Vasp, except the constructuin of the Bandstructure object by irrep.

**Comment by josueclavijo** [comment]
**Respected Stepan, I'm honored, and really thanks for taking the time to answer my queries. The code now works like a charm.**

Just to gain a deeper undestanding of your code, pardon me if i ask to you the following things:

**1 - Are critical to get meaningful results the following warnings, or should I just ignore them**

Warning 1

DeprecationWarning: dict interface (SpglibDataset['origin_shift']) is deprecated.Use attribute interface ({self.__class__.__name__}.{key}) instead

Warning 2

Neither refUC nor shiftUC were specified in CLI and searchcell was False. Taking 3x3 identity matrix as refUC and shiftUC=(0,0,0). If you want to calculate the transformation to conventional cell, run IrRep with -searchcell **???**


**2 - Can the constraint over the supercel size** (setting the transformation matrix to just being defined using integer numbers) **be modified so the transformation matrix could be espressed using any rational or decimal numbers?** this is because when relaxing supercells, the transformation matrix with respect to an also relaxed unit cell is not always an integer number relationship, due to the minute changes in forces acting over atoms that arise as a function of the different functional used in the supercell and unit cell relaxations calculations...

**Comment by bmondal94** [comment]
Hi @josueclavijo ,

1. We have just released BandupPy latest version (v-0.3.4). The 'Warning' msgs are fixed in the latest version. Feel free to upgrade Banduppy to the latest version at your convenience.
The new version additionally includes: 
a. irrep latest version (>=1.9.3) support
b. Major upgrade of effective mass calculation function
c. Added quantum espresso tutorial

2. Interesting. If the second question still requires further discussion, we propose to open a topic in our [Discussions section](https://github.com/band-unfolding/banduppy/discussions). 

Since the issue related to the code has been resolved, I will now proceed to close this issue.

**Comment by stepan-tsirkin** [comment]
@josueclavijo 

Sorry, during the summer I missed your question. Regarding (2), as I understand 

1. You start from a primitive unit cell defined by a vectors (3x3) matrix A (columns are lattice vectors)
2. Construct a supercell $C = N\cdot A$ (where $N$ has all integer elements)
3. distort and relax the supercell somehow, that no the supercell is presented by the matrix $C' \approx C$
4. Now you should unfold to the primitive cell formed by vectors $A' = N^{-1} C'$
5. Because $C' = N A'$, where $N$ are integers, the procedure will work

Technically, the procedure may be generalized to rational coefficients, but so far I do not see much sense in it. 

Say, in id you have a primitive cell period $a$, and supercell period $c$, so that $c = \frac{m}{n}a$. This is like unfolding a supercell $nc$ to $a$, so like you first "fold $n$ times your supercell and then unfold $m-times$" . Probably it is equivalent to "unfold $m$ and then fold $n$" which does not sound very useful, although may be done as a post-unfolding procedure.
